### PR TITLE
fix(service-workers): tweak sw settings

### PR DESCRIPTION
**Pull request by amcdnl**
This PR tweaks the ngsw settings for update mode to use prefetching. It also upgrades Angular to 6.0.9 for various fixes to SWs.

Reference issue: https://github.com/angular/material2/issues/11945

### CODE REVIEW

**Comment by CDDelta** [comment]
Build outputs were changed in Angular 6. They will need to be updated in order to properly cache them, maybe change that in this PR while you're at it.  [For reference](https://github.com/angular/devkit/commit/fb78b20b5b5d46795f31b03ce3c02ed25432bee6#diff-dba244caa12fc352f91127ba5efc49e4).

**Comment by jelbourn** [comment]
@amcdnl looks like the change mentioned by @CDDelta is relevant here

**Comment by amcdnl** [comment]
@jelbourn - Updated :)

**Comment by jelbourn** [comment]
@amcdnl just needs a quick rebase it seems

**Pull request closed without merging**
