### PR TITLE
fix: remove duplicated meta tag

### PR DESCRIPTION
**Pull request by USSDlover**
Remove duplicated meta tag for `theme-color` at line 48 and keep the tag at line 14

### CODE REVIEW

**Comment by USSDlover** [comment]
@googlebot I signed it!

**Review by Splaktar — CHANGES_REQUESTED** [review]
Thank you for catching this and working on a fix!

This one should actually be kept and the first one should be removed.

**Comment by USSDlover** [comment]
> Thank you for catching this and working on a fix!
> 
> This one should actually be kept and the first one should be removed.

Please, it is my honor!

The first meta tag has been removed and the second one added.

**Comment by USSDlover** [comment]
> Thank you for catching this and working on a fix!
> 
> This one should actually be kept and the first one should be removed.

**Review by Splaktar — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
