### PR TITLE
feat: Add the version number to the page.

### PR DESCRIPTION
**Pull request by josephperrott**

### CODE REVIEW

**Comment by jelbourn** [comment]
I don't really like the way this looks. How about we put it in the footer?

**Comment by amcdnl** [comment]
@jelbourn - Where would you like this to be in the footer?  Maybe here img

**Comment by jelbourn** [comment]
I was thinking in the empty space left of the copywrite

**Comment by willshowell** [comment]
Pinging, since the latest release has demoed the usefulness of this.

**Comment by jelbourn** [comment]
@josephperrott rebase?

**Comment by josephperrott** [comment]
@jelbourn rebased.  Though I never updated to change the placement of the versioning.

I have concerns for the placing it in the footer on mobile, I think it will be hard to discover as the footer looks busier.

**Comment by willshowell** [comment]
It should probably go where a multiple-version select would be (https://github.com/angular/material.angular.io/issues/168), right? Maybe in the sidenav like [material.angularjs.org](https://material.angularjs.org)?

**Comment by TheRedD0t** [comment]
I like the design with a select of the versions like at [material.angularjs.org](https://material.angularjs.org), too! Why reinvent the wheel?

**Comment by willshowell** [comment]
Any updates on this? Would hate to see it missed for the next release.

**Comment by jelbourn** [comment]
We'll have something to switch between versions eventually. For now I think we can start in the footer and explore from there

**Comment by ericruiz-developer** [comment]
So will these conflicts be addressed and merged or is this not happening any longer? Version would be really help IMO.

**Pull request merged**
