### PR TITLE
Svg theme classes

### PR DESCRIPTION
**Pull request by FrankiePo**
fix svg classes after @jelbourn commit 1ccf573a80127ea0af89a33db4906e54b5310741

### CODE REVIEW

**Comment by jelbourn** [comment]
@FrankiePo I don't follow what this PR is doing. Can you elaborate?

**Comment by FrankiePo** [comment]
fix stroke
After
image
Before
image

fix progress indicator
Before
image
After
image

**Comment by FrankiePo** [comment]
@ajitsinghkaler I haven't added class="docs-svg-primary-light-60-stroke" to `fastandconsistent.svg`. It was incorrectly added by @jelbourn in 1ccf573a80127ea0af89a33db4906e54b5310741
So the node looks like:
 ```
<use xlink:href="#fac-b" ... class="docs-svg-primary-light-60-fill"stroke="#00BCD4" class="docs-svg-primary-light-20-stroke" ...>
```
I fixed this by combining multipple classes in one attribute:
```
<use xlink:href="#fac-b" ... class="docs-svg-primary-light-60-fill docs-svg-primary-light-20-stroke" .../>
```

**Comment by ajitsinghkaler** [comment]
@jelbourn can you please check these changes and merge these changes.

**Comment by Splaktar** [comment]
This is even more obvious using one of the dark themes:

### Before
Screen Shot 2019-12-12 at 20 48 29

### After
Screen Shot 2019-12-12 at 20 48 37

### Before
Screen Shot 2019-12-12 at 20 48 54

### After
Screen Shot 2019-12-12 at 20 49 02

**Pull request merged**
