### PR TITLE
Fix 100% height in docs-guide

### PR DESCRIPTION
**Pull request by afnecors**
## Before 
image

## Fixed
image

### CODE REVIEW

**Comment by Splaktar** [comment]
I can reproduce this when the viewport height is very small.

**Review by Splaktar — CHANGES_REQUESTED** [review]
With this change, I get double vertical scrollbars

Screen Shot 2021-05-13 at 20 36 01

**Comment by afnecors** [comment]
Hi @Splaktar should I convert it to draft?

**Comment by Splaktar** [comment]
@afnecors if it's not ready for review, then that would be a good idea, yes.

**Comment by afnecors** [comment]
Ok @Splaktar it's ready for review. :)

**Comment by Splaktar** [comment]
Thank you for your work on this. Unfortunately, I got busy with other things and wasn't able to come back and review this quick enough. PR https://github.com/angular/material.angular.io/pull/1007 fixed this and was already merged.

**Pull request closed without merging**
