### PR TITLE
fix(readability): changed text opacity from .54 to .87 according the spec

### PR DESCRIPTION
**Pull request by EladBezalel**
fixes https://github.com/angular/material2/issues/2689

### CODE REVIEW

**Comment by EladBezalel** [comment]
| Before | After |
| ------- | ----- |
| image | image  |

**Comment by jelbourn** [comment]
I think the white-on-blue of the header also needs to be changed, as it's pretty low ratio now as well.

**Comment by EladBezalel** [comment]
@jelbourn @kara @amitafr - regarding the header - it seems like the `font-weight` right now is `300`, should i change it to `400` or do you have anything else in mind?

**Comment by andrewseguin** [comment]
Hey Elad, can you rebase this change

**Comment by EladBezalel** [comment]
@andrewseguin @kara rebased :)

**Comment by davidglezz** [comment]
Text still at .54

**Pull request merged**
