### PR TITLE
fix(component-sidenav): apply CSS fixes from master to 8.x

### PR DESCRIPTION
**Pull request by Splaktar**
Cherry pick a couple CSS fixes from `master`.

### CODE REVIEW

**Comment by Splaktar** [comment]
I'd like to pull these fixes into the `8.x` branch so that we can release them to production prior to `9.0.0`. @donroyco can you please consent as explained above in https://github.com/angular/material.angular.io/pull/654#issuecomment-541412190?

**Comment by donroyco** [comment]
@googlebot I consent.

**Comment by Splaktar** [comment]
Thanks!

**Comment by donroyco** [comment]
@Splaktar You're welcome!

**Pull request merged**
