### PR TITLE
add datepicker scene

### PR DESCRIPTION
**Pull request by annieyw**
First draft: 
datepicker scene

### CODE REVIEW

**Comment by mmalerba** [comment]
I think this one is escaping your color filter because of the overlay. It might be easier to just use a `<mat-calendar>` instead of a full `<mat-datepicker>`.

**Comment by annieyw** [comment]
image

**Comment by mmalerba** [comment]
can we change the gray colors on the circles, days of the week, and dropdown arrow - they don't fit great with the color scheme

**Comment by annieyw** [comment]
image

**Comment by mmalerba** [comment]
What do the 2 white circles represent anyways? At first I thought it was the selected date, but then why are there 2 of them. That also reminds me, we should make one of these show a range selection, since we just added that feature

**Comment by annieyw** [comment]
image

will update scene to use date range picker after 10.0

**Comment by mmalerba** [comment]
@annieyw needs rebase

**Pull request merged**
