### PR TITLE
feat: add missing component icons

### LINKED ISSUE #463: Missing icons for existing/new components
Some of the icons for material components are missing/not created as of now.

- [x] Badge
- [x] Bottom Sheet
- [x] Divider
- [x] Expansion Panel
- [ ] Form field (not sure for this)
- [x] Paginator
- [x] Sort header
- [x] Stepper
- [x] Table
- [x] Tree

Component Category - Popups & Modals

EDIT: I've done the icons which are available in this shared Sketch file: https://sketch.cloud/s/EGv8x

### PR DESCRIPTION
**Pull request by EdricChan03**
P.S. I'm not really good at designing icons.

The icons are based on a 100x100 grid.

Here's the Sketch file if needed: https://sketch.cloud/s/EGv8x

Closes #463

### CODE REVIEW

**Comment by Splaktar** [comment]
This is awesome! Thank you! I have been hoping to get a community contribution for this for over a year now 😄

**Comment by Splaktar** [comment]
Please rebase to pick up the fixes in PR https://github.com/angular/material.angular.io/pull/518 so that lint and CI will pass.

**Comment by Chan4077** [comment]
Thanks! I've rebased the PR as requested.

---

(P.S. Can there be some form of documentation on the different types of classes used to theme the component SVG icons?)

**Comment by Splaktar** [comment]
@Chan4077 I think that just about anyone can leave a review on a GitHub PR. In this case with an approval, it's just a 👍. Don't worry 😃

**Comment by HZooly** [comment]
@Chan4077 @Splaktar Indeed that was just a "Good change, thanks" haha ☮️

**Comment by Chan4077** [comment]
Any updates on the state of this PR? It's been about 5 months.

**Comment by Splaktar** [comment]
Sorry for the delays on this. The only feedback that I've seen from @jelbourn is that he might want to go in a different direction and wasn't sure if he was happy with these designs.

**Comment by jelbourn** [comment]
Yeah, I'm planning on us eventually redoing this site and I'm not sure we'll keep the icons since we don't have anyone on the team to actively maintain them.

**Comment by EdricChan03** [comment]
Any updates?

**Comment by jelbourn** [comment]
We have someone working on improving the site now; I'm heavily leaning towards deleting all of the component icons since we're going to get rid of the category pages.

**Comment by Splaktar** [comment]
@EdricChan03 thank you for your contribution here and I'm sorry that we couldn't make use of it. I think that we can close this PR now?

**Comment by EdricChan03** [comment]
I suppose we no longer need to merge this PR right?

The component list was recently removed in 09f92c662dd2b402b9a5b7f379367e4f958f6448 in favour of a list that lists all of the components.

**Pull request closed without merging**
