### PR TITLE
build: update to Angular and CLI v12 next.7 and Components v12 next.5

### PR DESCRIPTION
**Pull request by Splaktar**
- fix typing change in `ActivatedRoute.fragment`
- fix [breaking change](https://github.com/angular/angular-cli/pull/20361) to no longer allow the styles `bundleName` to include a path in the ng build config

### CODE REVIEW

**Comment by Splaktar** [comment]
It looks like these test typing errors with `components-examples` may be related to needing PR https://github.com/angular/components/pull/22390 to land with Angular 12.0.0-next.7 support prior to our docs site moving to that version.

**Review by wagnermaciel — APPROVED** [review]
lgtm

**Comment by wagnermaciel** [comment]
@Splaktar You have a CircleCI failure here but otherwise LGTM

**Comment by Splaktar** [comment]
I'll update now that PR https://github.com/angular/components/pull/22390 is merged and CI should be good to go.

**Pull request merged**
