### PR TITLE
build: ng update CLI and core. update to NodeJS 16.6.0

### PR DESCRIPTION
**Pull request by Splaktar**
- update StackBlitz for v13-next
- update firebase-tools
- fix dependabot issues
- update to `marky@1.2.2` to support NodeJS 16.x

Closes #1038. Closes #1040. Closes #1042.

### CODE REVIEW

**Comment by devversion** [comment]
@Splaktar CI seems to be red, is that being addressed as part of this PR?

**Comment by Splaktar** [comment]
@devversion yeah, I'll take a look at that ASAP.

**Review by zarend — DISMISSED** [review]

**Comment by Splaktar** [comment]
The CI failures are due to NodeJS 16.6.0 and the `marky` dependency of lighthouse: https://github.com/GoogleChrome/lighthouse/issues/12439

I'll update the lock file to use `marky@1.2.2` which should solve this.

**Comment by Splaktar** [comment]
@devversion fixed Lighthouse in CI to support NodeJS 16.x. All 🟢  now.

**Review by devversion — APPROVED** [review]

**Pull request merged**
