### PR TITLE
chore(style): added polish to code snippet examples

### PR DESCRIPTION
**Pull request by amcdnl**
Polishes the inline code example styles by adding ascent colors and padding.

**light**
light

**dark**
dark

### CODE REVIEW

**Comment by amcdnl** [comment]
@jelbourn - I think in another PR i'd like to convert the highlighter theme to actual material. Thoughts?

**Comment by jelbourn** [comment]
@amcdnl yeah, that would be great. We just grabbed off-the-shelf themes for expedience

**Comment by jelbourn** [comment]
(it's there's an existing material theme that would be even better)

**Comment by amcdnl** [comment]
@jelbourn - There is a dark material one ( https://github.com/Kelbster/highlightjs-material-dark-theme ) but not a light one.

**Pull request merged**
