### PR TITLE
fix api docs content from displaying after the left nav

### PR DESCRIPTION
**Pull request by andrewseguin**
Fixes issue introduced in #651

### CODE REVIEW

**Comment by Splaktar** [comment]
It's not clear what the issue was, but based on the fix, it looks like there were some layout problems on mobile?

@donroyco FYI

**Comment by Splaktar** [comment]
Oh, I see it...
Screen Shot 2019-10-17 at 23 00 12

**Comment by Splaktar** [comment]
Also applying to `8.x` branch in PR https://github.com/angular/material.angular.io/pull/658.

**Comment by donroyco** [comment]
Thanks @andrewseguin. How could I have overlooked this?

**Pull request merged**
