### PR TITLE
feat(stackblitz): add new stackblitz template to run harness test examples

### PR DESCRIPTION
**Pull request by annieyw**
demo with button harness example: https://material2-docs-dev.web.app/components/button/examples

### CODE REVIEW

**Comment by mmalerba** [comment]
@annieyw can you update the demo, it looks like it doesn't have the latest version of the code

**Comment by mmalerba** [comment]
Note: The inclusive language check is failing because of `import-blacklist` in `tslint.json`. Unfortunately there is currently no alternative name for that property.

**Comment by annieyw** [comment]
cleaned up template and updated demo: https://material2-docs-dev.web.app/components/button/examples

**Comment by mmalerba** [comment]
Thanks Annie! Looks awesome, really excited to finally have examples for our harnesses!! 🎉

**Pull request merged**
