### PR TITLE
fix: guides overlapping footer on narrow screens

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes that the guide tiles can overlap the footer on smaller screens.

Fixes https://github.com/angular/components/issues/22860.

### CODE REVIEW

**Review by devversion — APPROVED** [review]
LGTM. tested locally.  Looks like a unit test fails though: 

```
Chrome Headless 90.0.4430.72 (Linux x86_64) GuideList should set the footer below the bottom of the given view FAILED
	Error: main content should take up the full given height: Expected 1103 to be 1200.
```

**Comment by crisbeto** [comment]
I decided to remove the test. It just doesn't feel like something that we should be verifying in a unit test.

**Comment by devversion** [comment]
agreed 👍

**Comment by Splaktar** [comment]
There was already some work in progress for this that a contributor was helping with in https://github.com/angular/material.angular.io/pull/985.

**Pull request merged**
