### PR TITLE
docs(getting started.html and theming.html)

### PR DESCRIPTION
**Pull request by ladyleet**
Change style.css to styles.css in theming.html, add link reference to materialpalette.com and explain link to material design spec better, fix broken link in getting-started.html to theming.html.

### CODE REVIEW

**Comment by JFrankfurt** [comment]
I was about to fix the links too. Following the format from the [guide list] template (https://github.com/angular/material.angular.io/blob/master/src/app/pages/guide-list/guide-list.html) this should just be `href="/guide/theming`.

**Comment by ladyleet** [comment]
@JFrankfurt i'll edit it now thanks for the fyi!

**Comment by ladyleet** [comment]
@JFrankfurt updated! @kara @jelbourn hopefully this small change helps the nav of the docs and provides a little better experience. ;) updated styles.css as well on the material2 repo to match https://github.com/angular/material2/pull/2551

**Comment by EladBezalel** [comment]
lgtm!

**Comment by ladyleet** [comment]
@EladBezalel 👍

**Comment by jelbourn** [comment]
These docs are auto-generated from the markdown files in the material2 repo, so the changes would be wiped out the next time we update them. We're due for an update this week.

**Pull request closed without merging**
